title: "Laboratorio TESLA - UNSAAC"
email: contacto@unsaac.edu.pe
description: >-
  Laboratorio de Tecnología en Energías Renovables, Ingeniería de Comunicaciones Ópticas y Tecnología Medioambiental de la UNSAAC.
baseurl: "" # dejar vacío para repositorios tipo usuario.github.io
url: "https://laboratoriotesla-unsaac.github.io"
markdown: kramdown
